export { default as Logo } from './Logo'
export { default as Link } from './Link'
export { default as Hero } from './Hero'
export { default as Aim } from './Aim'
export { default as Belief } from './Belief'
export { default as Kids } from './Kids'
export { default as Teachers } from './Teachers'
export { default as Researchers } from './Researchers'